"""empty message

Revision ID: 063c0b5a9daa
Revises: 
Create Date: 2025-11-21 22:28:29.375818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by alembic.
revision = '063c0b5a9daa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by alembic - please adjust! ###
    op.create_table('users',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end alembic commands ###


def downgrade():
    # ### commands auto generated by alembic - please adjust! ###
    op.drop_table('users')
    # ### end alembic commands ###
