"""empty message

Revision ID: 30f568b849d4
Revises: 79daa44a0ec4
Create Date: 2025-11-24 16:48:01.755310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by alembic.
revision = '30f568b849d4'
down_revision = '79daa44a0ec4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['pid'], ['products.pid'], ),
    sa.ForeignKeyConstraint(['uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    # ### end alembic commands ###


def downgrade():
    # ### commands auto generated by alembic - please adjust! ###
    op.drop_table('orders')
    # ### end alembic commands ###
