"""empty message

Revision ID: 48a2c4306176
Revises: 063c0b5a9daa
Create Date: 2025-11-22 22:17:49.543830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by alembic.
revision = '48a2c4306176'
down_revision = '063c0b5a9daa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by alembic - please adjust! ###
    op.create_table('products',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('product_price', sa.Float(), nullable=False),
    sa.Column('product_stock', sa.Integer(), nullable=False),
    sa.Column('product_description', sa.String(), nullable=False),
    sa.Column('product_category', sa.String(), nullable=False),
    sa.Column('product_image', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('pid')
    )
    # ### end alembic commands ###


def downgrade():
    # ### commands auto generated by alembic - please adjust! ###
    op.drop_table('products')
    # ### end alembic commands ###
