"""empty message

Revision ID: 55d525eeebc4
Revises: 30f568b849d4
Create Date: 2025-11-24 18:59:20.860938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by alembic.
revision = '55d525eeebc4'
down_revision = '30f568b849d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by alembic - please adjust! ###
    
    # change 1: rename table to 'ordereditems' (removed dash)
    op.create_table('orderedItems',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('product_price', sa.Integer(), nullable=False),
    sa.Column('line_total', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.ForeignKeyConstraint(['pid'], ['products.pid'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    
    with op.batch_alter_table('orders', schema=None) as batch_op:
        # change 2: comment out this line to prevent the sqlite error
        # batch_op.drop_constraint(none, type_='foreignkey')
        
        # this line is enough. sqlite will rebuild the table and drop the old 'pid' column
        # along with its constraints automatically.
        batch_op.drop_column('pid')

    # ### end alembic commands ###


def downgrade():
    # ### commands auto generated by alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pid', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'products', ['pid'], ['pid'])

    op.drop_table('ordered-items')
    # ### end alembic commands ###
