"""empty message

Revision ID: 79daa44a0ec4
Revises: 48a2c4306176
Create Date: 2025-11-22 22:58:51.889370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by alembic.
revision = '79daa44a0ec4'
down_revision = '48a2c4306176'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_rating', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('product_reviews', sa.Integer(), nullable=False))

    # ### end alembic commands ###


def downgrade():
    # ### commands auto generated by alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('product_reviews')
        batch_op.drop_column('product_rating')

    # ### end alembic commands ###
