"""empty message

Revision ID: a4d2c33da7ca
Revises: 55d525eeebc4
Create Date: 2025-11-26 16:05:52.949840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by alembic.
revision = 'a4d2c33da7ca'
down_revision = '55d525eeebc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by alembic - please adjust! ###
    op.create_table('wishlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pid'], ['products.pid'], ),
    sa.ForeignKeyConstraint(['uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('product_rating',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('product_reviews',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end alembic commands ###


def downgrade():
    # ### commands auto generated by alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('product_reviews',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('product_rating',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.drop_table('wishlist')
    # ### end alembic commands ###
